### ISSUE TITLE
Update plugins paths

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/network-meter#6]
During the review of #5, it was noted that some paths need to be updated. For example, `plugins/ooni/main.json` contained the path of traceroute. All of those should be fixed.

**Comment by 0xPoly** [comment]
Ping updated here: https://github.com/measurement-kit/network-meter/commit/f3a3611926aea5fe4ed744e1144884f7d31abde7

**Comment by bassosimone** [comment]
Great!

Was wondering how are we going to support differences among operating systems as far as external commands not installed by us are concerned. For example, `ping` could be installed at `/usr/bin` rather than at `/bin` on another Unix system; on Windows the executable is `ping.exe` and the location is IIRC `C:\Windows\System32`.

Any idea / plan to deal with these issues?

**Comment by 0xPoly** [comment]
I was thinking of packaging different plugins for each OS. For example a ping-windows that works only on Windows, a ping-linux, etc. The only issue with this approach is that it creates quite a bit of fragmentation. 

The other approach is specifying paths for windows, linux and macos all in the same plugin and choosing the correct one based on the OS we are running on. However this means that if the developers want to include a binary, the plugin will have to be 2-3 times larger than is needed.

Thoughts on the matter?

**Comment by bassosimone** [comment]
Considering that different operating system may implement similar commands with not only different names but also different command line switches, I'd say that probably the first approach is easier to maintain in the longer period. Also, consider the case in which you have a command on certain systems only but not in other systems, well... in that case it's probably simpler to prepare a plugin for certain systems only.

I am not sure I fully understand what you mean when you say that "... if the developers want to include a binary, the plugin will have to be 2-3 times larger than is needed". Can you please elaborate on that?

**Comment by 0xPoly** [comment]
If we have "universal" plugin that uses a compiled binary (for example an nmap plugin) it will need to include both the windows .exe and the Linux/Mac executables, even though it will be only run on one of those operating systems. This could result in a plugin that is many times larger in size than it needs to be.

**Comment by bassosimone** [comment]
Thanks, now it's clear! So this is another argument against multi-operating-system plugins.

**Comment by bassosimone** [comment]
Ok, to wrap up, I'd say that we agree on having different plugins for family of operating system (or probably with a finer granularity). I think that those should probably be part of the repository so that one could test network-meter from any operating system (macos, windows, linux). Do you agree?

**Comment by 0xPoly** [comment]
>  should probably be part of the repository so that one could test network-meter from any operating system (macos, windows, linux)

I am unsure whether to include the plugins as part of this repository. It would be easier for those cloning the project if they were included, but I feel it would be more organized if we included the plugins in a different repo.

Maybe we should include a limited number of demonstration plugins in this repo?

**Comment by bassosimone** [comment]
> Maybe we should include a limited number of demonstration plugins in this repo?

Yes, I agree. Just a few plugins so that one can test the mechanism without cloning / fetching further stuff.

**Comment by 0xPoly** [comment]
I've summarized the discussion in #20
